### PR TITLE
Account for Display Aspect Ratio in video dimensions

### LINKED ISSUE #7: Weird aspect ratio for videos with different sample_aspect_ratio and display_aspect_ratio
I haven't been able to dig too deep into this yet, but it seems like for certain videos the aspect ratio of the generated thumbnails is off. For example, I have a landscape video with an aspect ratio of 4:3 (landscape) but the generated thumbnail has ratio of 2:3 (portrait).

I'd share the video but that would be a violation of copyright. I'll see if I can find a sample creative commons video soon that has this issue.

Looking at the output of the the ffprobe call for the video I have, I see different values for `sample_aspect_ratio` and `display_aspect_ratio` which I suspect might be causing this issue.

```js
   { streams:
      [ { index: 0,
          codec_name: 'h264',
          codec_long_name: 'H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10',
          profile: 'High',
          codec_type: 'video',
          codec_time_base: '1/60',
          codec_tag_string: 'avc1',
          codec_tag: '0x31637661',
          width: 320,
          height: 480,
          coded_width: 320,
          coded_height: 480,
          has_b_frames: 2,
          sample_aspect_ratio: '2:1',
          display_aspect_ratio: '4:3',
          pix_fmt: 'yuv420p',
          level: 21,
          color_range: 'unknown',
          color_space: 'unknown',
          color_transfer: 'unknown',
          color_primaries: 'unknown',
          chroma_location: 'left',
          field_order: 'unknown',
          timecode: 'N/A',
          refs: 1,
          is_avc: 'true',
          nal_length_size: 4,
          id: 'N/A',
          r_frame_rate: '30/1',
          avg_frame_rate: '30/1',
          time_base: '1/15360',
          start_pts: 0,
          start_time: 0,
          duration_ts: 2664453,
          duration: 173.466992,
          bit_rate: 304836,
          max_bit_rate: 'N/A',
          bits_per_raw_sample: 8,
          nb_frames: 5204,
          nb_read_frames: 'N/A',
          nb_read_packets: 'N/A',
          tags: { language: 'und', handler_name: 'VideoHandler' },
          disposition:
           { default: 1,
             dub: 0,
             original: 0,
             comment: 0,
             lyrics: 0,
             karaoke: 0,
             forced: 0,
             hearing_impaired: 0,
             visual_impaired: 0,
             clean_effects: 0,
             attached_pic: 0,
             timed_thumbnails: 0 } },
        { index: 1,
          codec_name: 'aac',
          codec_long_name: 'AAC (Advanced Audio Coding)',
          profile: 'LC',
          codec_type: 'audio',
          codec_time_base: '1/44100',
          codec_tag_string: 'mp4a',
          codec_tag: '0x6134706d',
          sample_fmt: 'fltp',
          sample_rate: 44100,
          channels: 2,
          channel_layout: 'stereo',
          bits_per_sample: 0,
          id: 'N/A',
          r_frame_rate: '0/0',
          avg_frame_rate: '0/0',
          time_base: '1/44100',
          start_pts: 970,
          start_time: 0.021995,
          duration_ts: 7699683,
          duration: 174.595986,
          bit_rate: 119746,
          max_bit_rate: 128000,
          bits_per_raw_sample: 'N/A',
          nb_frames: 7519,
          nb_read_frames: 'N/A',
          nb_read_packets: 'N/A',
          tags: { language: 'und', handler_name: 'SoundHandler' },
          disposition:
           { default: 1,
             dub: 0,
             original: 0,
             comment: 0,
             lyrics: 0,
             karaoke: 0,
             forced: 0,
             hearing_impaired: 0,
             visual_impaired: 0,
             clean_effects: 0,
             attached_pic: 0,
             timed_thumbnails: 0 } } ],
```

### PR DESCRIPTION
**Pull request by kj800x**
Resolves #7 

I was able to find some time for generating some sample videos that reproduced the issue described in #7.

I've iterated on my solution a few times, until I've come to this solution which seems to work on every weird video I throw at it. My final solution is to:
1. If the file contains a `display_aspect_ratio` (DAR), simply use the width* of the samples and the DAR to calculate the correct height for the display resolution.
2. If the file doesn't contain a valid `display_aspect_ratio`, but contains a valid `sample_aspect_ratio` (SAR), use the SAR and the width & height of the samples to calculate a display resolution.
3. If the file has neither a DAR or a SAR, assume the file uses square pixels and use the sample resolution as-is for the display resolution.

I've also added logic for automatically selecting the correct stream (select the first one with `codec_type === "video"`), as I ran into a few video files where the audio stream was stream 0 and the video stream was stream 1.

\* From what I've been able to find, it would also be valid to start with the height to calculate the width and it's up to the video viewer to decide which strategy to use (they might chose to use one over the other depending on the orientation of the video). Since we're just calculating the resolution just to downscale to the thumbnail size, I don't think it matters much which strategy we go with.

### CODE REVIEW

**Comment by RyanAfrish7** [comment]
Thanks for the PR. 

I have one minor concern. I am not sure whether multiplying by SAR is the right thing to do. 
> If the file doesn't contain a valid display_aspect_ratio, but contains a valid sample_aspect_ratio (SAR), use the SAR and the width & height of the samples to calculate a display resolution.

I think when DAR is invalid or absent, we should go with square pixels assumption.

> I've also added logic for automatically selecting the correct stream (select the first one with codec_type === "video"), as I ran into a few video files where the audio stream was stream 0 and the video stream was stream 1.

I see. I should stop making any assumption while coding.

**Comment by kj800x** [comment]
> I have one minor concern. I am not sure whether multiplying by SAR is the right thing to do.

I think the case where there's a DAR but not a SAR is pretty rare, so it's definitely an edge case. I think the definition of the SAR is that it scales the width of the pixels, so the display width would be the number of pixels * the SAR. That said, I don't think it's a huge issue, and if we wanted to just assume square pixels inside, that's fine. Lemme know and I'll make the change.

> I see. I should stop making any assumption while coding.

To be fair, your assumption held for almost every file I threw at it :smile:

**Comment by RyanAfrish7** [comment]
My understanding says SAR ratio must be equal to ratio of width to height attribute in JSON. If that's the case with any of the video you have, let's remove the SAR fallback logic.

**Comment by kj800x** [comment]
@RyanAfrish7 How does it look now? :)

**Comment by RyanAfrish7** [comment]
LGTM

**Pull request merged**
